### ISSUE TITLE
Empty bindings.json file breaks build

### ISSUE THREAD

**Issue by lucsoft** [littledivy/deno_bindgen#30]
- [ ] When deno_bindgen errors out it creates a empty bindings.json which should be fixed
- [ ] Marko should check before if the file is a valid json if not recreate it

**Comment by littledivy** [comment]
@lucsoft I believe this was fixed in #28 
Does this still happen if you use the CLI and Rust crate from the `main` branch?

**Comment by lucsoft** [comment]
@littledivy yes it still happens and I'm on main

**Comment by littledivy** [comment]
Ah okay. Just to confirm this is how you updated to `main`? :-)

```toml
# Cargo.toml
[dependencies]
deno_bindgen = { git = "https://github.com/littledivy/deno_bindgen", rev = "60a6f8a" }
```

```bash
deno install -n deno_bindgen -f -A --unstable https://raw.githubusercontent.com/littledivy/deno_bindgen/main/cli.ts
```
